### ISSUE TITLE
[ToDo List] A lot of vore features on mobs have been neglected, here's a list of a few I noticed

### ISSUE THREAD

**Issue by SpadesNeil** [CHOMPStation2/CHOMPStation2#6660]
#### Description
A lot of vore features on mobs have been neglected, broken, not set up right for the way they are actually used, or are unintuitive. This issue report is just a long list of weird things I've noticed that I should be able to fix as soon as someone helps me re-learn how to use Github.

#### List of things I could fix
- [ ] Vore mobs lack a default internal sprite because Chompers changed over to a system of colorable overlays, which is frankly better in every way, but it also means this feature got busted. This is the first thing I want to fix.
- [ ] Space sharks don't do vore, but they do have a vore sprite under vore64x64.dmi that isn't used for some reason.
- [ ] Jelly blobs should do bump noms since they otherwise do literally nothing but wander.
- [ ] Change gaslamps to digest instead of absorb because otherwise they accumulate wandering mobs which disables them from doing anything. They were originally set to absorb at request of Scree on Virgo, but this design choice is bad when other mobs clutter the map besides gaslamps.
- [ ] A ton of things could have more interactive insides like the dragons do. Nobody has done this yet. I will start doing this.
- [ ] Give _all the things_ custom belly text and emotes because I am a sane and rational individual with a modest amount of free time.
- [ ] I want a vore plant POI god damn it.
- [ ] More vorny POIs for the surface reeeee I am so sick of spiders everywhere by default.
- [ ] Make horse mobs inescapable through the front. Mostly to showcase belly interacts for other devs to then use as a reference. Also we have zero full tour mobs.
- [ ] Oties having Grut capitalized annoys me.
- [x] I've already written up vore text for carp, I just haven't added it yet. Space Sharks will also get this text.

#### List of things I can't fix because it's outside of my skill set so I need help
- [ ] _**TEACH ME HOW TO USE GITHUB AGAIN 🅰️🅰️🅰️🅰️🅰️🅰️🅰️🅰️🅰️🅰️🅰️🅰️🅰️**_
- [ ] Normal snakes have no vore sprites even though they should. Not to be confused with giant snake. See snake_vr.dmi or make a new snake sprite.
- [ ] Kururak have no vore sprites. See 64x64.dmi
- [ ] The giant snake sprite is horrible and was a placeholder as one of our first vore mobs in Virgo and I sorely want to replace it with something less horrible. It's in vore64x64.dmi
- [ ] Cows are something that should have vore sprites, but don't. Better yet, a new 32x64 sprite cow mob.
- [ ] Someone added the ski game yeti but didn't add vore sprites?! What?! What's even the god damn point?! See animal_VG.dmi
- [ ] A lot of the hostile cultist/syndicate/converted could do with some vore sprites. Why? Why the hell not? :B
- [ ] Some kind of code that if you pet a horse while targeting its mouth it homfs you.
- [ ] More aquatic preds. How about space orcas that I can throw in the nearby water? Or eels? Or ice sharks? But I don't know how to make mobs aquatic only, nor can I sprite that.

#### Code Revision
https://github.com/CHOMPStation2/CHOMPStation2/commit/012af587aa23d3428c96ac0967015c00215318f0

#### Also...
If you know of anything I missed, let me know. Someone's gotta start chipping away at this shit, might as well be me.

**Comment by SpadesNeil** [comment]
Oi! This is not stale! In fact, there have been several slow but steady changes!
