### ISSUE TITLE
TGChat Feedback/Issue Thread

### ISSUE THREAD

**Issue by ItsSelis** [CHOMPStation2/CHOMPStation2#7390]
To check / Reproduce:
- [x] State of hotkey mode weirding out
- [x] OPEN | https://github.com/VOREStation/VOREStation/issues/15657 **NOTE:** This probably is a skin issue of the button not properly switching back to the chat? Maybe the cork/bulletin board itself might be at fault too.

ToDo:
- [x] OPEN | Chat sometimes not initializing correctly on round start (Bandaided for now)
- [x] OPEN | #7436  (/icon issue)
- [ ] OPEN | #7400
- [ ] OPEN | Hovering over verbs should show command in statusbar

In Progress:
- [ ] IN PROGRESS (Selis) | Retaining only a certain amount of days for logs (to combat https://github.com/VOREStation/VOREStation/issues/15599) (related: https://github.com/CHOMPStation2/CHOMPStation2/issues/7432)
- [x] IN PROGRESS (Selis) | #7581

Complete:
- [x] DONE (Kashargul) | Ability to basically remove the highlighted message from the highlighter (not being there again in the next round)
- [x] DONE (Kashargul) | https://github.com/VOREStation/VOREStation/issues/15602
- [x] DONE (Selis) | Custom localstore to prevent messages from other servers (namely tg etc.)
- [x] DONE (Selis) | Ability to enable/disable ping warnings (or making them dismissable)
- [x] DONE (Selis) | Statusbar bugged (showing ready instead of examine)
- [x] DONE (Selis) | Old colors back (implemented via themes)
- [x] DONE (Selis) | More matching of colors of skin elements
- [x] DONE (Selis) | #7401
- [x] DONE (Kashargul) | Chat highlights ignoring own messages if possible
- [x] DONE (Kashargul) | Using an emoji as 1. letter will cause the �� issue.
- [x] DONE (Kashargul) | Export chatlog verb
- [x] DONE (Kashargul) | Ability to reorder the chat tabs
- [x] DONE (Kashargul) | #7433
- [x] DONE (Kashargul) | Chat export not respecting filters
- [x] DONE (Kashargul) | The main tab is currently deleteable
- [x] DONE (Kashargul) | Hitting tab to switch out of hotkey mode will undo the dark background theming for that lower toolbar, while preserving the white text, making it impossible to actually see what you are typing.
- [x] DONE (Selis) | #7399 (Awaiting tgui 5.0: https://github.com/VOREStation/VOREStation/pull/15583 https://github.com/VOREStation/VOREStation/pull/15608 https://github.com/VOREStation/VOREStation/pull/15635)
- [x] DONE (Kashargul) | Logging export filter (stuff that gets seen in chat but not exported into file)
- [x] DONE (Kashargul) | Timestamps as chat setting for local time to replace the server time one for players on tg chat (would use a checkbox in the chat to enable)

**Comment by ItsSelis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [tgchat fixes and featues](https://trello.com/c/xxPrQCoC/42-tgchat-fixes-and-featues)

**Comment by Kashargul** [comment]
Using an emoji as 1. letter will cause the �� issue.

**Comment by Kashargul** [comment]
Chat highlights ignoring own messages if possible --> https://github.com/VOREStation/VOREStation/pull/15623

**Comment by Kashargul** [comment]
Ability to basically remove the highlighted message from the highlighter (We now also store them if emptied)
OPEN | https://github.com/VOREStation/VOREStation/issues/15602 (We allow links in the custom URL section for OOC notes as well as in LOOC / OOC to be parsed)
--> https://github.com/VOREStation/VOREStation/pull/15626

**Comment by Kashargul** [comment]
OPEN | Hitting tab to switch out of hotkey mode will undo the dark background theming for that lower toolbar, while preserving the white text, making it impossible to actually see what you are typing.
 
 -> https://github.com/VOREStation/VOREStation/pull/15638
 
 we'll remove that static colour change for now.

**Comment by Kashargul** [comment]
OPEN | Chat sometimes not initializing correctly on round start
 
 -> sadly related to the addition of the oldchat option in the ping subroutine.

**Comment by Kashargul** [comment]
New Open: https://github.com/VOREStation/VOREStation/issues/15657

**Comment by Kashargul** [comment]
The wish for a temporary dismiss button directly on the banner has been voiced multiple times. I'll see about that when I look into the chat code next time.

**Comment by Runa-Dacino** [comment]
I am surprised this hasn't been reported yet. So I went and reported it:

https://github.com/VOREStation/VOREStation/issues/15799

MoTD is broken upstream, not sure if it's broken here as well.

**Comment by Runa-Dacino** [comment]
https://github.com/VOREStation/VOREStation/issues/15822
